# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Sahaptin Tenino spellchecker"
tqn = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Sahaptin Tenino, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
tqn = "TRANSLATE: A spellchecker for Sahaptin Tenino, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.tqn"

[windows]
system_product_code = "{DF4370F6-4EEE-46D2-866D-1A724285DF5D}_is1"

[package.speller]
name = "Sahaptin Tenino"
version = "0.1.0"

[package.grammar]
name = "Sahaptin Tenino"
version = "0.1.0"

[package.tts-textproc]
name = "Sahaptin Tenino"
version = "0.1.0"

[package.hyphenator]
name = "Sahaptin Tenino"
version = "0.1.0"
