template = "https://github.com/giellalt/template-lang-und"
rev_id = 275
template_sha = "ae7f0a90eca4365746c3ec57f8e39437abd6d807"

[replacements]
__GLOTTOLOG_ID__ = "teni1238"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tqn"
__UND2C__ = "tqn"
__UNDEFINED__ = "Sahaptin Tenino"
__UND__ = "tqn"
