template = "https://github.com/giellalt/template-lang-und"
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "teni1238"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tqn"
__UND2C__ = "tqn"
__UNDEFINED__ = "Sahaptin Tenino"
__UND__ = "tqn"
