template = ""
rev_id = 204
template_sha = "e2882c9d970daa8699f93d44a4d2440eae448af4"

[replacements]
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tqn"
__UND2C__ = "tqn"
__UNDEFINED__ = "Sahaptin Tenino"
__UND__ = "tqn"
